name: Déploiement Production

on:
  push:
    branches:
      - main
      - US4-CI/CD

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Repas
    steps:
      - uses: actions/checkout@v2

      - name: Setup .Net 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      
      - name: Restore dotnet dependencies
        run: (dotnet restore)
      
      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Unit Tests
        run: dotnet test -c Release --no-build